name: "BanInfo"
main: BanInfo\Loader
api: 3.0.1
version: 1.2.4 [RUS]
authors: [TableStudio Team (TSt), "WeekThor"]
description: "Информация о бане"
permissions:
  baninfo.commands.baninfo:
    description: '/bi'
    default: op
  baninfo.commands.banip:
    description: '/bi-ip'
    default: op
  baninfo.commands.bancid:
    description: '/bi-cid'
    default: op